version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: root # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: root1234 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: test # The PostgreSQL default database (automatically created at first launch)
